auth:
  password: <path:development/data/sample-secret#lab-secret>
master:
  resources:
    requests:
      cpu: "0"
      memory: "0Mi"
    limits:
      cpu: "2"
      memory: "1Gi"
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
replica:
  resources:
    requests:
      cpu: "0"
      memory: "0Mi"
    limits:
      cpu: "2"
      memory: "1Gi"
metrics:
  enabled: false
  resources:
    requests:
      cpu: 0
      memory: 0Mi
    limits:
      cpu: 150m
      memory: 192Mi
  serviceMonitor:
    enabled: true
    namespace: "prometheus"
